api/knowledge_base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('knowledge_control.urls')),
]

api/knowledge_control/urls.py
from django.urls import path, include

from . import views

app_name = 'knowledge_control'

urlpatterns = [
    path("", views.tests_list, name="list"),
    path("<int:test_id>/attempt/", views.attempt_test, name="attempt"),
    path("<int:test_id>/attempt/answer/", views.answer_question, name="answer"),
    path("<int:test_id>/attempt/<int:attempt_id>/finish/", views.finish_test, name="finish"),
    # API urls
    path("api/", include("knowledge_control.api_urls")),
]

api/knowledge_control/models.py
from django.db import models
from django.contrib.auth.models import User


class Discipline(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.title or 'New discipline'


class Topic(models.Model):
    discipline = models.ForeignKey(
        Discipline,
        null=True,
        on_delete=models.SET_NULL)

    title = models.CharField(max_length=255)
    description = models.TextField()
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.title or 'New Topic'


class Test(models.Model):
    topic = models.ForeignKey(
        Topic,
        null=True,
        on_delete=models.SET_NULL)

    title = models.CharField(max_length=255)
    description = models.TextField()
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.title or 'New Test'


class Question(models.Model):
    text = models.TextField()
    test = models.ForeignKey(
        Test,
        related_name='questions',
        on_delete=models.CASCADE)

    def __str__(self):
        return self.text or 'New question'


class Option(models.Model):
    text = models.TextField()
    correct = models.BooleanField()
    question = models.ForeignKey(
        Question,
        related_name='options',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.text or 'New option'


class Attempt(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True)

    def is_finished(self):
        return self.test.questions.count() == self.answer_set.count()


class Answer(models.Model):
    attempt = models.ForeignKey(Attempt, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answered_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)
    selected_options = models.ManyToManyField(Option)

    class Meta:
        unique_together = [
            ['attempt', 'user', 'question']
        ]

    def is_correct(self):
        incorrect_answers = self.selected_options.filter(correct=False).count()

        if incorrect_answers > 0:
            return False

        correct_answers = self.selected_options.filter(correct=True).count()
        correct_options = self.question.option_set.filter(correct=True).count()

        return correct_answers == correct_options

api/knowledge_control/forms.py
from django import forms

from .models import  Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['selected_options']

api/knowledge_control/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.utils import timezone

from .models import Test, Attempt, Answer
from .forms import AnswerForm
from .utils import get_test_and_attempt, get_current_question


def tests_list(request):
    context = {
        'tests': Test.objects.filter(published=True)
    }
    return render(request, 'knowledge_control/tests-list.html', context)


def attempt_test(request, test_id):
    test, attempt = get_test_and_attempt(test_id, request.user)
    question = get_current_question(test, attempt)

    context = {
        'test': test,
        'attempt': attempt,
        'question': question,
    }

    return render(request, 'knowledge_control/attempt-test.html', context)


def answer_question(request, test_id):
    test, attempt = get_test_and_attempt(test_id, request.user)
    question = get_current_question(test, attempt)

    answer = Answer(
        attempt=attempt,
        user=request.user,
        question=question,
    )

    form = AnswerForm(data=request.POST, instance=answer)

    if not form.is_valid():
        raise Exception(form.errors)

    form.save()

    redirect_url = reverse('knowledge_control:attempt', args=[test.id])
    return redirect(redirect_url)


def finish_test(request, test_id, attempt_id):
    test = get_object_or_404(Test, pk=test_id)
    attempt = get_object_or_404(Attempt, pk=attempt_id, test=test)

    if attempt.finished_at is None:
        attempt.finished_at = timezone.now()
        attempt.save(update_fields=['finished_at'])

    result = {
        'correct_answers': len([
            1
            for row in
            attempt.answer_set.all() if row.is_correct()
        ]),
        'total_questions': test.questions.count()
    }
    result['grade'] = round(result['correct_answers'] / result['total_questions'] * 10)

    context = {
        'test': test,
        'attempt': attempt,
        'result': result,
    }

    return render(request, 'knowledge_control/finish-test.html', context)

api/knowledge_control/templates/knowledge_control/attempt-test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test attempt #{{ attempt.id }}</title>
</head>
<body>

{% if question %}
<p>{{ question.text }}</p>
<form method="POST" action="{% url 'knowledge_control:answer' test.id %}">
    {% csrf_token %}
    {% for row in question.options.all %}
    <label>
        <input type="checkbox" name="selected_options" value="{{ row.id }}">
        {{ row.text }}
    </label>
    {% endfor %}

    <button type="submit">Ответить</button>
</form>
{% else %}
<p><a href="{% url 'knowledge_control:finish' test.id attempt.id %}">Завершить тест и получить оценку</a></p>
{% endif %}

</body>
</html>

api/knowledge_control/templates/knowledge_control/finish-test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результаты теста #{{ attempt.id }}</title>
</head>
<body>
    <h1>{{ test.title }}</h1>
    <p>{{ request.user.first_name }} {{ request.user.last_name }} завершил тест с {{ attempt.started_at }} по {{ attempt.finished_at }}</p>

    <table>
        <thead>
        <tr>
            <th>Правильные ответы</th>
            <th>Всего вопросов</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ result.correct_answers }}</td>
            <td>{{ result.total_questions }}</td>
        </tr>
        </tbody>
    </table>

    <hr>
    <h2>{{ result.grade }} баллов</h2>

    <a href="{% url 'knowledge_control:list' %}">Вернуться на главную</a>
</body>
</html>

api/knowledge_control/templates/knowledge_control/tests-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test list</title>
</head>
<body>
    <ul>
        {% for row in tests %}
        <li><a href="{% url 'knowledge_control:attempt' row.id %}">{{ row.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>